### ISSUE TITLE
Update versions and example files

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/ladybug#120]
@chriswmackey please let me know once you think it is ok to change the versions and start updating example files! Both Ladybug and Honeybee issues are closed for the Jan. release

**Comment by agusHariyadi** [comment]
Some of the example have been broken with the new version component, ie mannequin component in UTCI example (1 - Ladybug Comfort Tutorials - Outdoor Comfort: UTCI) or 2 - Getting Started With Ladybug - Visualizing Data on the Colored Chart didn't give me chart anymore..
I haven't try all the examples file..

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,
We are ready.  I just finished off the last of the major checks that I had to do on the components.
LET'S DO THIS!!

**Comment by mostaphaRoudsari** [comment]
Thanks @chriswmackey!

Hi @agusHariyadi , Thank you for reporting. I will make sure to double check but can you please give me more details about the errors?

**Comment by mostaphaRoudsari** [comment]
Components are updated!
Still I need to update example files...

**Comment by agusHariyadi** [comment]
@mostaphaRoudsari  , sorry not give you specific error, I have already give Chris one of them  (mannequin component error (#123)) and have already being fixed. and I see some other has already reported and being fixed, I will report again when I find one.
I just though that because you give user specific step for user ( "Instructions for Installing Ladybug + Honeybee:
(Follow steps 1-6 for basic functionality and 1-11 for full functionality)"), in step 11 you pointed to Chris video tutorial, https://www.youtube.com/playlist?list=PLruLh1AdY-Sj_XGz3kzHUoWmpWDXNep1O
  I think this will be the first place that they will see, and as ordinary newbie, they will follow step by step process and some times some of them are easily frustrated if in the middle of the step the component give them error.. So I agree with you that maybe re-uploaded the updated file examples in which @chriswmackey already uploaded before in each video will help them so much..

**Comment by mostaphaRoudsari** [comment]
Thanks @agusHariyadi! I just updated all the example files for Honeybee and Ladybug and also installation files. There are a couple that live on Chris's dropbox and I think he will update them tomorrow. We should be good for releasing new version tomorrow afternoon.
