### ISSUE TITLE
Bug? - Solar Adjust Temperature

### ISSUE THREAD

**Issue by arkdanielnielsen** [mostaphaRoudsari/ladybug#122]
I wanted to use @chriswmackey 's example file about Shade Benefit Evaluation, but it gives very high numbers. This means the data cannot be used further with e.g. Shade Benefit. 
Link to the updated example file:
https://www.dropbox.com/s/t3zlwvitwqxpt3o/018_OutdoorShadeBenefitEvaluation.gh?dl=0
![ladybug_solaradjust-01](https://cloud.githubusercontent.com/assets/7299731/5967541/4ac24eb2-a80e-11e4-9cd6-61a9d238e8b9.JPG)

**Comment by chriswmackey** [comment]
@arkdanielnielsen ,

There was a bug in the GenCum component that @mostaphaRoudsari just fixed yesterday.  Update to the latest version and all should be well.  Good to know that you are on top of the bugs as much as we are :)

-Chirs

**Comment by arkdanielnielsen** [comment]
Thanks for the quick respond.
I am just wondering if the result is still correct (I have updated all components). The temperature is getting up to 79 degree at some points?
![ladybug_solaradjust-02](https://cloud.githubusercontent.com/assets/7299731/5972346/4a708cb8-a858-11e4-8edf-d7337c83a912.JPG)

**Comment by chriswmackey** [comment]
@arkdanielnielsen ,

Those values seem to be in the right range.  Sitting in the sun for a full hour can keep you pretty warm.  Also, remember that those numbers are only adjusted MRT and the radiant environment usually only accounts for half of the heat loss from the human body (the other half is to the air).  So you can imagine that the total Temperature Delta is about half of the MRT delta that you have there. Lastly, the geometry of the human body can have a big effect on the Temperature Delta so I would check to be sure that the mannequin is not staring into the sun, which I have found can give unusually high deltas.

-Chris

**Comment by arkdanielnielsen** [comment]
I understand, thanks.
I have a other problem. I have specified a specific analysis period. After I did that there is this error message "1. Solution exception:index out of range: 1950". Any idea of why this message?
![ladybug_solaradjust-03](https://cloud.githubusercontent.com/assets/7299731/5989002/1a438f42-a978-11e4-913a-6d9e792a6e93.JPG)

**Comment by chriswmackey** [comment]
@arkdanielnielsen ,
That should not happen.  Can you post the GH file?
-Chris

**Comment by arkdanielnielsen** [comment]
Yes:
https://www.dropbox.com/s/t3zlwvitwqxpt3o/018_OutdoorShadeBenefitEvaluation.gh?dl=0

**Comment by chriswmackey** [comment]
@arkdanielnielsen ,
You were right that it was a bug.  I just fixed it.  Also, for a climate like Norway where the area of shade desirability is so small, you should really boost up the sky resolution to 4. Otherwise, such a small patch can get lost between sky two patches.
![image](https://cloud.githubusercontent.com/assets/5567574/5992145/4086f286-a9e9-11e4-931e-3bebd5893fdf.png)
https://www.dropbox.com/s/x2ooz3vr7ffvnm2/018_OutdoorShadeBenefitEvaluation_CWM.gh?dl=0
-Chris

**Comment by arkdanielnielsen** [comment]
Thanks for the tips Chris.
I have tried to increase the resolution in both the "Shade Benefit" and "GenCumulativeSkyMtx" and every time it freeze. If I decrease it works. Is it just the system that cannot handle that amount of data?

**Comment by arkdanielnielsen** [comment]
Maybe I should add where it happens. It happen when I plug the MRT data from "Outdoor Solar Adjusted Temperature Calculator" into the "Outdoor Comfort Calculator".

**Comment by chriswmackey** [comment]
@arkdanielnielsen ,
I would not increase the resolution of the "GenCumulativeSkyMtx" since this is really a lot of data for the solar adjusted temperature to process and you would not really get much more accurate results.  In fact, you can do away with the GenCum component altogether and just use the direct and diffuse data from the ImportEPW and this level of accuracy is pretty good for the solar adjusted temperature component. (see the dropbox link in my old post)
Just increase the sky resolution on the shade benefit component to 4 and this should give you a good level of accuracy in the result.  Also, your computer should be able to handle that amount of data unless you use some crazy grid size for you mesh.
-Chris
