### ISSUE TITLE
Wish for "Ladybug_Average Data"

### ISSUE THREAD

**Issue by arkdanielnielsen** [mostaphaRoudsari/ladybug#128]
It could be useful to average the data for a whole year (annual) with the "Ladybug_Average Data". Or is there another component I have overlooked that can do that?

**Comment by chriswmackey** [comment]
@arkdanielnielsen ,
I would just use the LB "separate data" component and the native Grasshopper "Average Data" component.  However, if there's a good reason for this type of shortcut in a workflow, I can add it in.
-Chris

**Comment by arkdanielnielsen** [comment]
I found a solution, but there is a spelling mistake in the "Create LB Header" (1). See GH link:
https://www.dropbox.com/s/zpejqkv4p6mx6zs/Ladybug_Wish_AverageData.gh?dl=0
I have also tried to edited a conversion component to get data in Wh instead of kWh (2). I could not manage to make it work 100%, only the conversion not the right text in the component.
![ladybug_wish_averagedata-03](https://cloud.githubusercontent.com/assets/7299731/6098008/34c76726-afd1-11e4-9cfe-111305d5a193.JPG)

**Comment by arkdanielnielsen** [comment]
The reason I needed it is I what to show results both annually and monthly. Now when there is the other possibilities I just think why is the annual not available?

**Comment by mostaphaRoudsari** [comment]
@arkdanielnielsen I added an extra output for average for the analysisPeriod and fixed the misspelled annual. Thanks for reporting.

![image](https://cloud.githubusercontent.com/assets/2915573/6101100/0fe52d1a-afec-11e4-9636-baa1e6ef4f60.png)

I'm not clear about the second wish though. Can you please help me to understand what you are looking for. I'm closing this issue since about average data component. We can follow up for the other wish in a separate discussion.
