### ISSUE TITLE
Issue and wish: LB_SolarAdjustTemperature - bodyLocation_

### ISSUE THREAD

**Issue by ayezioro** [mostaphaRoudsari/ladybug#152]
Hi,
I'm having some issues defining a different location for the mannequin but the default.
When no input is hooked to this item it is fine (of course) for all body positions. But when i hook a point the objects drops below the point or above it.
So the wish is that the coordinates of the mannequin will be calculated according to any input point and this point will be the lower one for all the positions.
Thanks,
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,

At the moment, the body location is set to be the height of a seat where the mannequin is sitting but I realize that this gets confusing wen the mannequin is standing up or lying down.  I can change it to be from the height of the mannequin's feet if this would be easier.

-Chris

**Comment by ayezioro** [comment]
Hi Chris,
The thing is that when you don't input the location the insertion point is "fine". I mean, the feet is always at the same location regardless the position (stand, seat, lying). But when you do input the location is less predictable.
So the answer to your question is yes, it would be easier (i guess).
Thanks,
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,
I have not changed the bodyLocation to be at the lowest part of the mannequin instead of the mannequin's center of gravity.  This should give a more consistent idea of where the bodylocation is expected to be as you scroll through different postures.
https://github.com/mostaphaRoudsari/ladybug/commit/efc3b05118a628e60c3ddea625840d20a22d6690
-Chris

**Comment by ayezioro** [comment]
Thanks Chris!!
