### ISSUE TITLE
Data matching in outdoor shade benefit component

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/ladybug#180]
@chriswmackey we are using the shade benefit component for the class and I noticed that there is a possible bug with data matching in the component. If user connects multiple regions to the component the component will crash unless temperatures and testshades follow the same data tree. The only way that I found to get the component to work was something like this which is not very elegant:

![image](https://cloud.githubusercontent.com/assets/2915573/10310512/4d3515d2-6c10-11e5-884e-09046300b7c2.png)

should we change line 121-125 to something similar to code below?
```python
        try: allDataDict[path]["shadeSrfs"] = _testShades.Branch(i)
        except: allDataDict[path]["shadeSrfs"] = _testShades.Branch(0)
        
        try: allDataDict[path]["temperatures"] = _temperatures.Branch(i)
        except: allDataDict[path]["temperatures"] = _temperatures.Branch(0)
```

Also why the component doesn't accept multiple regions?

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,

To be honest, I have not yet used this component  with more than one region for a given set of test shades (only for multiple shades for a single test region).  Any time that I have had multiple test regions, I have wanted to align them with a respective set of shades so that the component does not take a very long time to run (long run meaning that it calculates every possible effect of each test shade on each region).

I feel that I should preserve this current branching functionality since I find it so useful but I should also include the ability to have multiple test regions per shade if people want to run the long calculation route. I should also note that the deeper reason why this bug exists is that the energy shade benefit evaluator has a different set of beam gains for each window (or region), thereby necessitating that you have just one window per given shade set (there might be a better way of dealing with this by adding beam gains if the two windows belong to the same zone by this whole process gets really difficult for a multizone model if you don't do this branching). For comfort benefit, this is easier since you have only one temperature per zone or outdoor area.

Along with the fixing of  this bug, I also want to implement the automatic breaking down of polysurfaces into individual surfaces, since polysurfaces into the current component causes it too produce weired results.

I will try to fix this soon.
-Chris

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,
This is now fixed:
https://github.com/mostaphaRoudsari/ladybug/commit/de5601fcba89a84bedc0766a4da4624da0b45fba

You should be able to run the component with as much geometric freedom as you wish.  Now the only upgrades that remain here are related to the accuracy of the calculation.

Also, check out the updated hydra:
http://hydrashare.github.io/hydra/viewer?owner=chriswmackey&fork=hydra_2&id=Outdoor_Comfort_Shade_Benefit

-Chris
