### ISSUE TITLE
View Rose fails sometimes

### ISSUE THREAD

**Issue by bhowes-tt** [mostaphaRoudsari/ladybug#185]
I'm trying to make an animated walkthrough by calculating the view rose at a series of locations along a curve.  It works at some locations, fails at others:
Working:
![frame_00008](https://cloud.githubusercontent.com/assets/3171551/10619827/c0f6f9b4-7745-11e5-86cd-7bf602e04b16.jpg)

Failing:
![frame_00009](https://cloud.githubusercontent.com/assets/3171551/10619842/cf2419f4-7745-11e5-8b9c-779a59977029.jpg)

Here's a screenshot of the GH file for testing.  Try animating the slider that evaluates the curve - there are a few spots on there where the view rose fails.
![image](https://cloud.githubusercontent.com/assets/3171551/10619925/5761bb6e-7746-11e5-8ae4-2d4901f16e61.png)

**Comment by mostaphaRoudsari** [comment]
Hi @bhowes-tt! Thank you for reporting. I will look into this and report back.

**Comment by bhowes-tt** [comment]
I'll stay tuned @mostaphaRoudsari - THANKS!  :anchor: :boat: 

I've been showing this and the 3d view analysis tools off at Pratt this semester - Lots of interest over there!

**Comment by chriswmackey** [comment]
It seems we never looked into this issue and I have not been able to recreate it.  If anyone manages to produce an example file that recreates this issue, please post a link to it and we will look into it.

**Comment by mostaphaRoudsari** [comment]
Finally, After only two years[!] I checked issue and it seems the failure is because the building geometries are not modeled carefully and don't touch the XY plane. I move the curve for 1 meter up and everything works fine. @bhowes-tt sorry for the very late reply. I think we can now close this issue as the issue is not related to Ladybug component.

![image](https://user-images.githubusercontent.com/2915573/35231362-9069e882-ff66-11e7-8eb8-0e11884be217.png)

**Comment by bhowes-tt** [comment]
:+1: :heart: :octopus:
