### ISSUE TITLE
Large scale SVF and sun visibility

### ISSUE THREAD

**Issue by etienneburdet** [mostaphaRoudsari/ladybug#187]
Hello,

I tried to use LB to compute a large number of SVF on a scene (about 2000 points) using the LB_mask component. While it works great to compute 1 to a dozen SVF, once the number grows too large, it seems the component and/or LB cannot handle the large number of outputs (GH seems to be "loading" forever). A bit of the same problem appears for the "sunisvisible" variable of the sunlight hours: works great for a day to a month, but full year on 2000 points just crash the party again :(

A few test tells me we're not far from being able to do it though :
- Animating a slider on the 2000 points works perfectly. A bit slow because it writes 2000 files, but works fine.
- The radiation calculation works great on the same geometry, with the same grid and it's quite fast (and I guess it computes SVF and sunvisibility somewhere).

Maybe having an option to specify an outputfile where SVF are written one by one and/or an option to only compute the values without the viewport output would help ? I will try to have a look, but I am really bad at Python and never coded a GH plugin, so don't expect miracles here.

Thanks a lot for this excellent software, it really does a lot of things with awesome flexibility and interface with other softwares !

_P.S : In case you wonder, I'm computing SVF to embed them on an automated blind controller. Having SVF for each window helps us having less sensors. But it could also be useful for e.g. comparing different radiosity methods I think._

**Comment by mostaphaRoudsari** [comment]
Hi @etienneburdet. Sorry for the delay to get back to you.

I assume you're using shading mask component for this the analysis? Assuming that which sky density are you using and did lowering the sky density helps?
You're right the component is not designed for handling so many points, and animating sliders looks like a good solution you can write all the results to the same file using excel exporter components available from other Grasshopper plugins (TTToolBox, LunchBox, etc) to avoid 2000 files, or you can use "a" option in file. Try code below in a component assuming you have an input x on the component, this component will always append the new value to the end of the file "c:/ladybug/SVF.txt"
```python
with open("c:/ladybug/SVF.txt", "a") as outf:
        outf.write(str(x) + "\n")
```
Also you can right click on the component and turn off the view.

In both cases the reason that Grasshopper becomes slow is mainly because of datatree structure. We can't do much about this from our side. Radiation analysis component has to deal with less number of calculations since the number of sky patches is 145. Saying that I have ran sunlighthours analysis for master-plan projects  with no issues but then I never tried to do anything with the results of sunIsVisible output which will be a huge datatree.

I keep this issue open as I need to work on the component anyways at some point. They are mathematical solutions to address this calculation much faster than how Ladybug is doing it right now. Thank you for the note.

**Comment by etienneburdet** [comment]
Thanks ! 

Indeed, I came to the append solution too, which works perfectly. I have tried sky densities from 0 to 3 and it didn't reduce the calculation time drastically (I had to let the computer run and do something else for quite some times).

For the sunIsVisible part, I use direct radiation instead. It is much more faster.

If it is a data tree problem, indeed, there isn't much to do except sliders/append (which works).

**Comment by chriswmackey** [comment]
Since the time of this issue, we now have a newer, much faster way to compute sky view for a large number of points.  See this example file for calculating sky view throughout an urban canyon:
http://hydrashare.github.io/hydra/viewer?owner=chriswmackey&fork=hydra_2&id=Sky_View_in_an_Urban_Canyon&slide=0&scale=1&offset=0,0
