### ISSUE TITLE
PV components tab

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/ladybug#190]
@chriswmackey, @stgeorges should we keep PV components under WIP or are we moving them to the main tabs? I know that we're waiting for the latest modified version by Tuesday afternoon. Can you guys make a decision on the current status of the components. I know that we have #188  and #150 open for PV components.

@stgeorges can you add your comments to these issue and the other two? Thanks.

**Comment by stgeorges** [comment]
Hi @mostaphaRoudsari , @chriswmackey ,

The [#188](https://github.com/mostaphaRoudsari/ladybug/issues/188) was not opened due to incorrect working of Photovoltaics components.
As far as I know, we do not have an issue with [#150](https://github.com/mostaphaRoudsari/ladybug/issues/150) any more.
The only reason for not switching the components from the "WIP" would be some major flaw or an error, which is not what we currently have.
I do not see the reason for not switching the component from "WIP" tab to their tabs.

Of course, in the end I would have to wait for you two to decide on this.

**Comment by mostaphaRoudsari** [comment]
Hi @stgeorges! I can see this as two different topics. I agree that we can move the components from WIP since it has been proved that there is no major bugs in components.

On the other hand let's keep the discussions open until we come to a conclusion. Are you telling me that #150 has been already addressed? If that is the case then I would go ahead and close it. If anyone has a comment they will be able to re-open the issue. Thanks again for the components. They look great.

**Comment by stgeorges** [comment]
Hi @mostaphaRoudsari ,
I have no problem with both issues being open.
#150 had a number of questions. They have all be replied. Some have be resolved, some required an explanation. By taking a look at the issue again, I do not see the unresolved ones.
The same goes for #180 (at least for now), it's just it's much younger, so there might be new replies from Chris there.
Thanks for the kind words.

**Comment by chriswmackey** [comment]
@mostaphaRoudsari and @stgeorges ,

I apologize for being late here.  I agree that the components should be moved out of WIP for the release and I will post feedback on https://github.com/mostaphaRoudsari/ladybug/issues/188 once I get the chance.

-Chris

**Comment by chriswmackey** [comment]
This issue is old and I am about to open a new one to discuss the solar hot water components.
