### ISSUE TITLE
Saved Files: Components Not "Hearing" [Ladybug_Ladybug] on Open

### ISSUE THREAD

**Issue by StepMaher** [mostaphaRoudsari/ladybug#211]
Hey everyone,

I'm not sure if this has been discussed yet; I couldn't find anything during my (albeit quick) search.

I've built a few "plug and play" definitions that I continue to use or package and pass along to colleagues. I've noticed when I open them up not all the Ladybug or Honeybee components "hear" the main class component. I often have to Disable/Enable those components. This is specifically true with [Ladybug_Analysis Period], but has occurred with others as well. See image below.

![ladybug_hearing_impaired](https://cloud.githubusercontent.com/assets/10765460/11667214/672d332c-9dbe-11e5-9e03-6a74076d498e.jpg)

This isn't a major issue so far, but it can seriously limit workflow (especially for those who're not familiar with GH).

I'm happy to provide any additional information.

Best,
/SPM

**Comment by chriswmackey** [comment]
@StepMaher ,

It is great to see you on github!  I hope things have been awesome since ACADIA.

The issue that you mention is because Grasshopper needs to read the libraries of LB_LB first before trying to run any other Ladybug components.  All grasshopper components in a given GH file are arranged in an order on the canvas with some components being read first when you open the file depending on the order that you dropped the components on the canvas.  You can send any component to the back of the grasshopper canvass by selecting them in hitting Cntrl + B on the keyboard.  If you do this for your Honeybee_Honeybee and Ladybug_Ladybug components, this will ensure that they load first next time that you open your grasshopper file.  This then ensures that all of your other components work in the file instead of telling you that you should let ladybug and honeybee fly.

Let me know if I am understanding you issue correctly and, if so, feel free to close out the issue.
-Chris

**Comment by StepMaher** [comment]
@chriswmackey,

Everything is going swimmingly, thanks! I hope you're well too.

That's a neat trick! (How did I not know that before?) It worked for what I was trying to accomplish. Thanks for the quick reply (as always).

Best,
/SPM
