### ISSUE TITLE
Microclimate Analysis error

### ISSUE THREAD

**Issue by ocni-dtu** [mostaphaRoudsari/ladybug#215]
Hey,

When I try to run the microclimate analysis it displays an error saying: "1. The calculation has been terminated by the user!"
If I check the code it looks like the failure comes from the climateMapPMV function.
Have I made a setup mistake or is it a bug? 
Thanks!

https://www.dropbox.com/s/j0bcbhjhc085oqm/Microclimate%20analysis%20error.gh?dl=0

![error](https://cloud.githubusercontent.com/assets/16247318/11913508/2fb31ca8-a666-11e5-9550-68d1c42c926e.png)

**Comment by chriswmackey** [comment]
@ocni-dtu ,
Given the way that you have structured the GH file, I will need your IDF file and CSV result file in addition to the GH file.  If possible, I think that it would be best for you to upload a GH file that creates the HBZones and runs them through the energy simulation instead of uploading these other two files.
This should allow me to re-create your error and, once I get that, I should be able to fix the problem.  I was able to run the microclimate maps yesterday without much issue so hopefully this bug is small.
-Chirs

**Comment by ocni-dtu** [comment]
When I made the file this week, I didn't have any problems. It only happend today. So it is a bit weird.

Here's a link to the complete file. The comfort part is a bit messy, sorry
https://www.dropbox.com/s/861gtmxzdjyuy2b/Energi%20and%20comfort.gh?dl=0

**Comment by chriswmackey** [comment]
@ocni-dtu ,
I took a closer look at your file and I realized what the problem is.  You connected "Adaptive Comfort Parameters" to the PMV recipe component.  The PMV requires comfort parameters from the "PMV Comfort Parameters" component.  I have just put in an extra warning in the PMV recipe component to make sure that we catch this in future cases:
https://github.com/mostaphaRoudsari/Honeybee/commit/f272ebdc88313660ba2663c2dd51f553fa2acf48
and you can find a working GH file here:
https://www.dropbox.com/s/njx9pn06f4lde38/Microclimate%20analysis%20error_CWM.gh?dl=0
-Chris

**Comment by ocni-dtu** [comment]
Thank you!
