### ISSUE TITLE
Comfort % problem on Psychometric chart

### ISSUE THREAD

**Issue by MingboPeng** [mostaphaRoudsari/ladybug#312]
Hi Mostapha and Chris,

Just notice there is something wrong with comfort % on Psychometric chart. please check Thermal Mass, 8.5% is obvious not right. 

I double checked with "point in curves", found Thermal Mass and Evaporative cooling should be 48%, and comfort without strategies 39% (was 20.4%).

![image](https://cloud.githubusercontent.com/assets/9031066/19899139/4f3ff1e4-a035-11e6-95be-46f290c4a0d3.png)

Could you please double check with this? or I did something wrong.

Thanks in advance,
Mingbo

**Comment by mostaphaRoudsari** [comment]
Thanks @MingboPeng for reporting this. @chriswmackey should be able to answer your question. My best guess is that it gives you the % after removing the points which are already covered by other strategies. Can you remove evaporative cooling and occupant use of fans and see if the value changes to what you expect?

**Comment by MingboPeng** [comment]
@mostaphaRoudsari  Hi Mostapha, the result doesn't change, it is still 8.5% if I only keep Thermal Mass.

**Comment by chriswmackey** [comment]
@MingboPeng ,
I'm very sorry for the late reply.  I wrote the component to just give the points inside each polygon so it shouldn't be removing the points satisfied by the other strategies.  Also, the isPointInside command is exactly what is being used inside the Psych chart component so there should be agreement.

Perhaps there is an issue with another input on the component.  Are you using an analysis period or conditional statement?  Could you post a link to a GH file showing the issue?

-Chris

**Comment by MingboPeng** [comment]
Hi @chriswmackey ,

I found the problematic line in this component (line: 1592 "if strategyTextNames[countComf + countStrat + 1] != "Thermal Mass + Night Vent" or epwData == False or patternList != []:") . 

I don't understand why you exclude the "Thermal Mass + Night Vent" here. it gets the correct % when I remove this exclusion.

I have attached the gh file, for your debugging.

Please chek

![image](https://cloud.githubusercontent.com/assets/9031066/20458788/76a9a2ac-ae7c-11e6-8ff7-223c053a1599.png)

![image](https://cloud.githubusercontent.com/assets/9031066/20458791/852b1748-ae7c-11e6-8f2c-f0163e880ca5.png)

[PsyChart.zip](https://github.com/mostaphaRoudsari/ladybug/files/601760/PsyChart.zip)

**Comment by chriswmackey** [comment]
@MingboPeng ,

Thank you for reporting this and sorry for the late response.  There definitely seems to be an issue as this comparison with the native GH isPointInside is giving some different results for the thermal mass + night flushing:
![psychchartnotcorrect](https://cloud.githubusercontent.com/assets/5567574/20634818/ba9b4b6e-b322-11e6-8144-adf977c6462c.JPG)

However, the change that you made does not seem to be fixing it.  Let me look a bit deeper into it now.

-Chris

**Comment by chriswmackey** [comment]
Ah, Wait.  I know what's going on here.  I had made this component so long ago that I forgot why I put that line in there (the one that you found).  It's because, in order for you to be able to use thermal mass, you need the temperature to get cold enough within the last 12 hours.  So, even though the point is inside the polygon, it might not really be an hour that can be met with thermal mass and night flushing because the previous hours are so hot and are outside the comfort polygon.  This is why the percentage output from the component for thermal mass + night flushing is not as large as the direct isPointInside calculation.  Let me know if this makes sense to you but this is the same method that the climate consultant psych chart uses.  If you feel that this is too confusing of a way to estimate night flushing, we can also take out the Thermal Mass + Night Flushing polygon (I've already excluded a number of climate consultant polygons from the Ladybug psych chart because their methods of estimation did not make much sense).  For now, I'll close out the issue but feel free to reopen it if you think these changes are necessary.

**Comment by mostaphaRoudsari** [comment]
@chriswmackey your logic totally makes sense to me. It's great that we have it there, but we should find a way to communicate this with the user in a better way. I'm not sure how but I think it's a critical part of the process for teaching the users about the logics in calculation.

**Comment by devngc** [comment]
@chriswmackey,

Interesting discussion here. I have not checked inside the component, but by looking at the image you attached, it occurs to me that in this particular case the thermal mass strategy is really helping in the summer situation. I say this because the comfort polygon for thermal mass starts at about 24C DB. If I am not wrong, in New York, only during the period of June to mid-September, the outside air temperature goes above 24C.

In such a scenario, the thermal mass can delay the heat emission inside the space during the day, and when it really starts emitting heat inside during the night time, the night time ventilation kicks in and it could help in getting rid of that heat. That way this strategy could help.

Please correct me if I am not interpreting this correctly here.
