### ISSUE TITLE
Solar Water Heating - Discrepancies when changing number of rows

### ISSUE THREAD

**Issue by jacoposartore** [mostaphaRoudsari/ladybug#315]
Hello,

I created a definition to see if calculations with Ladybug and those made by the mechanical engineer I'm collaborating with were similar.
Everything is working great when choosing a single row system: we checked the Solar Fraction Per Year output and it is close to the percentage he gave me.
![image](https://cloud.githubusercontent.com/assets/8501837/19964648/3dbe6a6a-a1c3-11e6-9a14-8fa69b27cf23.png)

I tried also to split the panels on two rows but the percentage oddly changes into two percentages that, if summed, don't equalize the first one. Moreover, the system doubles its size.
![image](https://cloud.githubusercontent.com/assets/8501837/19964679/7ed4645a-a1c3-11e6-9531-b9c8ea051904.png)

Correct me if I am wrong, I remember that @stgeorges did these components (great work by the way!). Here is the file.
[Solar Water Multiple Panels Error.zip](https://github.com/mostaphaRoudsari/ladybug/files/569301/Solar.Water.Multiple.Panels.Error.zip)

P.S. Energy Load Per Area output of PV SWH System Size component is giving a null output in either case.

**Comment by stgeorges** [comment]
Hi @jacoposartore ,

Thank you for finding the bug!
It looks that last time when component was edited, I forgot to add this line to its end:

`energyLoadPerRowPerHour = energyLoadPerRowPerHourDataTree`

So now the energyLoadPerRowPerHour output works.

But this output is not meant to be used to calculate the optimal system size when there is more than 1 row. Let me explain why:

Solar Water Heating Surface component calculates the heatFromTankPerHour output based on the surface area. So essentially it threats the inputted _SWHsurface as one giant collector. Also if you input multiple surfaces to the _SWHsurface (like you just did), they will all be treated as separate giant collectors. This is why when you calculate the optimalSystemSize output from the "Solar Water Heating Performance Metrics" component, you are getting two same results: one for one inputted _SWHsurface, and another one for the other inputted _SWHsurface.
For example: a single _SWHsurface of area of 10m2, will generate the same amount of heatFromTankPerHour energy as five _SWHsurfaces each one being 2m2.

So in case of SWH systems, the point of using the "PV SWH system size" component is too see how much space (collectors space) would system of certain size (in kWt) require. Notice that when you increase the numberOfRows_ input, the area of each SWH row shrinks, to accommodate the total area required for that system size.

I changed your definition (attached below) so that only one single surface is used to calculate the optimalSystemSize, while that surface divided into rows is used to calculate the total space the collectors will take. It is also useful to understand how optimalSystemSize optimalTankSize are calculated. For your specific issue, you can take the annualSolarFraction and the overall space of all your SWH rows as the optimal design criteria.

Also, why are you using tilt angle 25 and azimuth 135?
If you run the Tilt Optimal Factor component it will calculate the optimal tilt and azimuth angles for Venice. For "precision_" input, I got 30 and 185.7 . That's 5% increase in annual solar radiation in comparison with 25 and 135 degrees. I understand that you are interested in summer period only, but surely most of those 5% will "come" during summer.
Do you think that orienting the SWH rows at the same azimuth as the roof beneath will result in largest available space for the SWH rows?

Please let me know if some of my questions/sentences were confusing or not clear enough.

[Solar Water Multiple Panels Error2.zip](https://github.com/mostaphaRoudsari/ladybug/files/572040/Solar.Water.Multiple.Panels.Error2.zip)

**Comment by chriswmackey** [comment]
Thanks for fixing this @stgeorges . Now that this issue is addressed, I am closing it out :)
