### ISSUE TITLE
Issue with Internalized EPW Weather Data

### ISSUE THREAD

**Issue by frank984** [mostaphaRoudsari/ladybug#371]
![cattura](https://cloud.githubusercontent.com/assets/6491927/23945341/792619e8-0976-11e7-9b58-5a04bb32efde.JPG)
[unnamed.zip](https://github.com/mostaphaRoudsari/ladybug/files/844171/unnamed.zip)

**Comment by chriswmackey** [comment]
@frank984 ,

This happened because you internalized the weather data as a text string and all of the ladybug components need to have the dates of the data be python tuples.  If you pass the data through a "Create LB Header" component to re-create the header, all of the data displays correctly:
![image](https://cloud.githubusercontent.com/assets/5567574/24054441/9cf3e114-0b12-11e7-8584-af13a6ef69ff.png)

Here's the file showing how:
https://www.dropbox.com/s/jpeilsdfczi1d9h/unnamed_CWM.gh?dl=0

The need for all of these components is unfortunately the result of us poorly structuring Ladybug when it was started four years ago.  The new revision of Ladybug that is in the works will be able to convert the text to python tuples so you won't have to go through this workaround.

-Chris
