### ISSUE TITLE
Mac OS compatibility

### ISSUE THREAD

**Issue by yafimski** [mostaphaRoudsari/ladybug#439]
Hello,
As I've spoken to Sarith here:
http://discourse.ladybug.tools/t/ladybug-tools-in-mac-problems-in-the-beginning/2284/6

I'm trying to achieve any kind of usability of LB/HB on Mac OS. Currently running:

Mac OS 10.13.3 (17D102)
Rhino for Mac 5.4.1
GH and GH-ArchiCAD live connection

Right now I'm trying to set up the folder structure correctly 
![folder_structure_mac_gh](https://user-images.githubusercontent.com/20420760/38126700-84cb88ee-33f2-11e8-8de3-54c71804fadd.png)

Here I'm a bit unclear about which .py files should sit in which component folder of GH etc.
Drag and drop isn't available on Mac as far as I can tell, it doesn't do anything.

Thanks :)

**Comment by chriswmackey** [comment]
@yafimski ,
It seems that the discussions that you have been having with @Sariths are about Honeybee[+] and so this issue does not belong under the legacy honeybee repository here.  Rather it should be posted to the Honeybee[+] repo here:
https://github.com/ladybug-tools/honeybee

We won't be easily able to get honeybee legacy to run on mac and so I'm going to close out this issue here.  I suggest you coordinate with @Sariths to get it working in the new HB+, which should be easier than trying to do it with the legacy and will have a much better pay-off in the long run.
