### ISSUE TITLE
Ladybug line chart type 2

### ISSUE THREAD

**Issue by sawjam** [mostaphaRoudsari/ladybug#454]
[errordatafile.txt](https://github.com/mostaphaRoudsari/ladybug/files/2666382/errordatafile.txt)
When using the attached data the chart fails with:
Runtime error (TypeErrorException): iteration over non-sequence of type NoneType

Traceback:
  line 427, in plotData, "<string>"
  line 506, in script
Chart 0 and chart 1 work fine.

**Comment by sawjam** [comment]
[errordatafile.txt](https://github.com/mostaphaRoudsari/ladybug/files/2666378/errordatafile.txt)
Data file for line chart type 2 error

**Comment by sawjam** [comment]
sorry closed it accidentally

**Comment by chriswmackey** [comment]
@sawjam ,
All of the data is displaying correctly after I imported and reformatted it:
![image](https://user-images.githubusercontent.com/5567574/49861589-30dfe200-fdca-11e8-905e-eb7bc239bac3.png)

Could you post a link to a file that recreates the issue?

**Comment by chriswmackey** [comment]
@sawjam ,

The issue was that one of your lists was entirely of 0 values, which make it difficult to draw an area chart since there is no area under the curve.  While I had a check for this when you plugged in only a single list of 0 values, I didn't have checks for when this type of data is alongside other data lists.  So I added a check here:
https://github.com/mostaphaRoudsari/ladybug/commit/f34254bd855e7b64d5d47d4995a3c1551f6c32e0
Ans, while you still won't get a mesh for this list of all 0 values, the component will still run for the other lists.
