### ISSUE TITLE
Test chamber component

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/ladybug#60]
This component will generate a test room based on users input and inserts a person so we can calculate an accurate radiation analysis to be used for MRT calculation.

**Comment by chriswmackey** [comment]
@mostaphaRoudsari , @claudioarchi ,

This issue seems very outdated and does not seem to belong under Ladybug (since it refers to energy simulation and should be under Honeybee).  As such, I am closing out this issue.

If the idea with this test chamber was just to be able to calculable MRT with a full human geometry, we should continue the discussion on the Honeybee issue that I created for this topic a while ago:
https://github.com/mostaphaRoudsari/Honeybee/issues/229

-Chris
