### ISSUE TITLE
Add a component to calculate sunrise and sunset time

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/ladybug#61]
Can be probably  merged into sun-path.

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,

I am just outlining the following things that I see this issue now referring to:

1) A component that calculates sunrise/sunset time of each day in an analysis period (realizing that this is different than what the sunpath does).

2) A component that takes several streams of annnualHourlyData and just spits out sunUp vs sunDown values for each data stream (making it easy to handle large lists of annualHourlyData like that which we get out of EnergyPlus runs).

3) An extra output of the sunpath called isSunUp that gives you a list of 8760 boolean values (for a year-long analysis period) that simply say is the sun up (1) or down (0).  This will save a few steps in the workflows where I currently use the sunPoitionsHOY.

4) An occupancy generator for Daysim that automoatically builds an occupancy schedule based on whether the sun is out (since I have noticed that this is fast becoming a standard in a lot of building codes and architecture practices).

-Chris

**Comment by mostaphaRoudsari** [comment]
@chriswmackey just wanted to update this issue that now we have a method that can calculate this:
https://github.com/ladybug-analysis-tools/ladybug-core/blob/master/ladybug/sunpath.py#L145-L168

I rather to keep this functionality for the new Ladybug but if it's critical we can integrate it to the current Ladybug too.

**Comment by chriswmackey** [comment]
Now that @AntonelloDN  has a component to do this, I think we should just move it out of WIP and include it in the next stable release.  @AntonelloDN , can you think of any reasons why the component should remain in WIP?

**Comment by AntonelloDN** [comment]
Hi @chriswmackey,
you can move the component out of WIP. If you think the code it is not cleaned we can change some parts of code ;)

Antonello

**Comment by chriswmackey** [comment]
@AntonelloDN ,
Thanks for confirming that the component seems good from your end. I'll move it out of WIP for the next release.

@mostapharoudsari ,
For clarification, all of the issues that I have highlighted for the next release have to do with moving existing components out of WIP that have been shown to be stable. I am not planning to add any more functionality to the legacy Ladybug and, as a means of typing up loose ends, I am moving the last stable components out of WIP. A number of components had gotten stuck in WIP that are stable but we're never moved because we had planned to make improved versions. Now that those improved versions will be happening in LadybugPlus, I am moving these stable components out of WIP for the next legacy release.

Let me know if you agree with this @mostapharoudsari .

**Comment by chriswmackey** [comment]
The component has been moved out of WIP via: https://github.com/mostaphaRoudsari/ladybug/commit/54939bd93adced4d87576443b180586f1ab58bb8

Case closed!
