### ISSUE TITLE
Wish / Idea - Text and Line Colors

### ISSUE THREAD

**Issue by arkdanielnielsen** [mostaphaRoudsari/ladybug#84]
When updating the example files it hit me, why is text and lines in black colors as default? I think it could be nice to have this as default instead of using the Custom Preview component.

**Comment by chriswmackey** [comment]
@mostaphaRoudsari and @arkdanielnielsen ,

If I am understanding this issue correctly, I am greatly opposed to automatically changing the default grasshopper display color (it's just going to make other things messy when people actually want to preview geometry other than our ladybug visualizations).  If we want nice graphics from the LB visualizations, I would rather focus on the bakeIt workflow (https://github.com/mostaphaRoudsari/ladybug/issues/104) rather than privileging the screenshot workflow that is already pretty solid now.

As such, I am closing out the issue.  If I am misunderstanding you, feel free to reopen.
-Chris
